/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceDevelopersRouteImport } from './routes/_workspace.developers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevelopersRoute = WorkspaceDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/developers': typeof WorkspaceDevelopersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/developers': typeof WorkspaceDevelopersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/developers': typeof WorkspaceDevelopersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authorize' | '/login' | '/dashboard' | '/developers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authorize' | '/login' | '/dashboard' | '/developers'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/authorize'
    | '/login'
    | '/_workspace/dashboard'
    | '/_workspace/developers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/developers': {
      id: '/_workspace/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof WorkspaceDevelopersRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDevelopersRoute: typeof WorkspaceDevelopersRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDevelopersRoute: WorkspaceDevelopersRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
